services:
  - type: web
    name: CS171
    region: ohio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api.application:app"
envVarGroups:
- name: verifiable-frontend